# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 600)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* ===============================\n"
"   GENEL ARKA PLAN\n"
"   =============================== */\n"
"QMainWindow {\n"
"    background-color: #E3E8E7;   /* açık ama profesyonel */\n"
"}\n"
"\n"
"/* ===============================\n"
"   BUTONLAR (KÖŞELİ & MODERN)\n"
"   =============================== */\n"
"QPushButton {\n"
"    background-color: #F4F6F8;\n"
"    color: #2C2C2C;\n"
"    border: 2px solid #8FAADC;\n"
"    border-radius: 6px;          /* hafif köşe – tam kare değil */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* ÜZERİNE GELİNCE */\n"
"QPushButton:hover {\n"
"    background-color: #DCE6F2;\n"
"    border-color: #5B9BD5;\n"
"}\n"
"\n"
"/* BASILINCA */\n"
"QPushButton:pressed {\n"
"    background-color: #BFD7EE;\n"
"    border-color: #2F75B5;\n"
"    padding-top: 12px;   /* basılma hissi */\n"
"    padding-left: 12px;\n"
"}\n"
"\n"
"/* ===============================\n"
"   ANA BAŞLIK LABEL\n"
"   =============================== */\n"
"QLabel {\n"
"    background-color: #2F4F4F;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* ===============================\n"
"   MENÜ & STATUS BAR\n"
"   =============================== */\n"
"QMenuBar {\n"
"    background-color: #D6DCDA;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #D6DCDA;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 240, 181, 71))
        self.pushButton_2.setStyleSheet("background-color:#BA55D3;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 400, 221, 71))
        self.pushButton_3.setStyleSheet("background-color:#DB7093")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 110, 221, 71))
        self.pushButton_4.setStyleSheet("background-color:#DDA0DD;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 240, 181, 71))
        self.pushButton_5.setStyleSheet("background-color:#FF00FF;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 411, 61))
        self.label.setStyleSheet("\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STOK UYGULAMASI ANA EKRAN"))
        self.pushButton_2.setText(_translate("MainWindow", "SATIŞ"))
        self.pushButton_3.setText(_translate("MainWindow", "STOK"))
        self.pushButton_4.setText(_translate("MainWindow", "ÜRÜNLER VE REÇETELER"))
        self.pushButton_5.setText(_translate("MainWindow", "SATIŞ LİSTELERİ"))
        self.label.setText(_translate("MainWindow", "AKYOKUŞ KASRI STOK TAKİP UYGULAMASI"))
