# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receteekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 649)
        MainWindow.setStyleSheet("/* =========================\n"
"   GENEL PENCERE\n"
"========================= */\n"
"QMainWindow {\n"
"    background-color: #D8BFD8;\n"
"    font-family: Segoe UI;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"\n"
"/* =========================\n"
"   ANA BAŞLIK LABEL\n"
"========================= */\n"
"QLabel#label {\n"
"    background-color: #1e1e1e;\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* =========================\n"
"   DİĞER LABEL’LAR\n"
"========================= */\n"
"QLabel {\n"
"    color: #333333;\n"
"}\n"
"\n"
"/* =========================\n"
"   BUTONLAR (GENEL)\n"
"========================= */\n"
"QPushButton {\n"
"    background-color: #2c7be5;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1a68d1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1454a3;\n"
"}\n"
"\n"
"/* =========================\n"
"   ANA EKRANA DÖN BUTONU\n"
"========================= */\n"
"QPushButton#pushButton_3 {\n"
"    background-color: #dc3545;\n"
"    font-size: 10pt;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton#pushButton_3:hover {\n"
"    background-color: #b52a37;\n"
"}\n"
"\n"
"/* =========================\n"
"   LINEEDIT (ARAMA vs)\n"
"========================= */\n"
"QLineEdit {\n"
"    padding: 6px;\n"
"    border-radius: 4px;\n"
"    border: 1px solid #aaa;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #2c7be5;\n"
"}\n"
"\n"
"/* =========================\n"
"   LİSTWIDGET\n"
"========================= */\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #2c7be5;\n"
"    color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   TABLE WIDGET\n"
"========================= */\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #e9ecef;\n"
"    padding: 4px;\n"
"    border: 1px solid #ccc;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* =========================\n"
"   SCROLLBAR (OPSİYONEL)\n"
"========================= */\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    background: #f1f1f1;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b0b0b0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #909090;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 261, 561))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 80, 251, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_ara = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ara.setGeometry(QtCore.QRect(400, 40, 121, 31))
        self.lineEdit_ara.setObjectName("lineEdit_ara")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 40, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(290, 110, 256, 192))
        self.listWidget_2.setObjectName("listWidget_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 530, 161, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 410, 101, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 350, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(290, 410, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 380, 351, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 9, 261, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 111, 31))
        self.label_2.setStyleSheet("  background-color: #dc3545;\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 350, 111, 31))
        self.label_3.setStyleSheet("  background-color: #dc3545;\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
" ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 320, 241, 31))
        self.label_4.setStyleSheet("  background-color: #1e1e1e;\n"
"    color: white;\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"    padding: 6px;")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "REÇETEYİ GÖSTER"))
        self.pushButton_2.setText(_translate("MainWindow", "ÜRÜN ARA"))
        self.pushButton_3.setText(_translate("MainWindow", "ANA EKRANA DÖN"))
        self.pushButton_4.setText(_translate("MainWindow", "KAYDET"))
        self.pushButton_5.setText(_translate("MainWindow", "SATIR EKLE"))
        self.label.setText(_translate("MainWindow", "ÜRÜNLER"))
        self.label_2.setText(_translate("MainWindow", "Ürün ismi:"))
        self.label_3.setText(_translate("MainWindow", "Ürün ismi:"))
        self.label_4.setText(_translate("MainWindow", "ÜRÜN VE REÇETE EKLE"))
