# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'satistakip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("/* =========================\n"
"   GENEL PENCERE\n"
"========================= */\n"
"QMainWindow {\n"
"    background-color: #C0C0C0;\n"
"}\n"
"\n"
"\n"
"/* =========================\n"
"   BAŞLIK\n"
"========================= */\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* =========================\n"
"   DATEEDIT & COMBOBOX\n"
"========================= */\n"
"QDateEdit,\n"
"QComboBox {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QDateEdit:focus,\n"
"QComboBox:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   LISTWIDGET (SATIŞ LİSTESİ)\n"
"========================= */\n"
"QListWidget {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   BUTONLAR (GENEL)\n"
"========================= */\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5dade2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e86c1;\n"
"}\n"
"\n"
"/* =========================\n"
"   ÖZEL BUTONLAR\n"
"========================= */\n"
"\n"
"/* Tarihe Göre Getir */\n"
"QPushButton#pushButton {\n"
"    background-color: #1abc9c;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background-color: #48c9b0;\n"
"}\n"
"\n"
"/* Ürüne Göre Getir */\n"
"QPushButton#pushButton_2 {\n"
"    background-color: #9b59b6;\n"
"}\n"
"QPushButton#pushButton_2:hover {\n"
"    background-color: #af7ac5;\n"
"}\n"
"\n"
"/* Ana Ekrana Dön */\n"
"QPushButton#pushButton_3 {\n"
"    background-color: #e74c3c;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton#pushButton_3:hover {\n"
"    background-color: #ec7063;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit_tarih = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_tarih.setGeometry(QtCore.QRect(340, 70, 231, 41))
        self.dateEdit_tarih.setObjectName("dateEdit_tarih")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 70, 191, 41))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 110, 271, 41))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 110, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 0, 361, 41))
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 60, 321, 491))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 450, 221, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "TARİHE GÖRE GETİR"))
        self.pushButton_2.setText(_translate("MainWindow", "ÜRÜNE GÖRE GETİR"))
        self.label.setText(_translate("MainWindow", "SATIŞ TAKİP RAPORLAMA"))
        self.pushButton_3.setText(_translate("MainWindow", "ANA EKRANA DÖN"))
