# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'satıs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        mainWindow.setStyleSheet("/* =========================\n"
"   GENEL PENCERE\n"
"========================= */\n"
"QMainWindow {\n"
"    background-color: #f4f6f9;\n"
"}\n"
"\n"
"/* =========================\n"
"   BAŞLIK LABEL\n"
"========================= */\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* =========================\n"
"   DATEEDIT - COMBOBOX - SPINBOX\n"
"========================= */\n"
"QDateEdit,\n"
"QComboBox,\n"
"QSpinBox {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QDateEdit:focus,\n"
"QComboBox:focus,\n"
"QSpinBox:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   LISTWIDGET\n"
"========================= */\n"
"QListWidget {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   BUTONLAR (GENEL)\n"
"========================= */\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5dade2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e86c1;\n"
"}\n"
"\n"
"/* =========================\n"
"   ÖZEL BUTONLAR\n"
"========================= */\n"
"\n"
"/* Listeye Ekle */\n"
"QPushButton#pushButton {\n"
"    background-color: #2ecc71;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background-color: #58d68d;\n"
"}\n"
"\n"
"/* Günü Kaydet */\n"
"QPushButton#pushButton_2 {\n"
"    background-color: #f39c12;\n"
"}\n"
"QPushButton#pushButton_2:hover {\n"
"    background-color: #f5b041;\n"
"}\n"
"\n"
"/* Bugüne Gel */\n"
"QPushButton#pushButton_3 {\n"
"    background-color: #95a5a6;\n"
"}\n"
"QPushButton#pushButton_3:hover {\n"
"    background-color: #b2babb;\n"
"}\n"
"\n"
"/* Ana Ekrana Dön */\n"
"QPushButton#pushButton_4 {\n"
"    background-color: #e74c3c;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton#pushButton_4:hover {\n"
"    background-color: #ec7063;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(10, 70, 191, 51))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(200, 70, 321, 51))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(520, 70, 121, 51))
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 70, 141, 51))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 150, 631, 231))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 150, 121, 231))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 460, 251, 91))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 431, 20))
        self.label.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SATIŞ SAYFASI"))
        self.pushButton.setText(_translate("mainWindow", "LİSTEYE EKLE"))
        self.pushButton_2.setText(_translate("mainWindow", "GÜNÜ KAYDET"))
        self.pushButton_3.setText(_translate("mainWindow", "BUGÜNE GEL"))
        self.pushButton_4.setText(_translate("mainWindow", "ANA EKRANA DÖN"))
        self.label.setText(_translate("mainWindow", "SATIŞ KAYIT SİSTEMİ"))
