# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stok.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 675)
        MainWindow.setStyleSheet("/* =========================\n"
"   GENEL PENCERE\n"
"========================= */\n"
"QMainWindow {\n"
"   background-color: #F0FFF0;\n"
"}\n"
"\n"
"/* =========================\n"
"   BAŞLIK LABEL (ÜSTTEKİ)\n"
"========================= */\n"
"QLabel#label_4 {\n"
"    color: #2c3e50;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"\n"
"/* Diğer label\'lar */\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* =========================\n"
"   TABLE WIDGET (STOK TABLOSU)\n"
"========================= */\n"
"QTableWidget {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 10px;\n"
"    gridline-color: #e1e5ea;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    padding: 6px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"\n"
"/* =========================\n"
"   LINEEDIT\n"
"========================= */\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"/* =========================\n"
"   DOUBLE SPINBOX\n"
"========================= */\n"
"QDoubleSpinBox {\n"
"    background-color: white;\n"
"    color: #2c3e50;\n"
"    border: 2px solid #cfd6df;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus {\n"
"    border: 2px solid #3498db;\n"
"}\n"
"\n"
"/* =========================\n"
"   BUTONLAR (GENEL)\n"
"========================= */\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5dade2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2e86c1;\n"
"}\n"
"\n"
"/* =========================\n"
"   ÖZEL BUTONLAR\n"
"========================= */\n"
"\n"
"/* Yeni Malzeme Ekle */\n"
"QPushButton#pushButton {\n"
"    background-color: #2ecc71;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    background-color: #58d68d;\n"
"}\n"
"\n"
"/* Stoğa Ekle */\n"
"QPushButton#pushButton_2 {\n"
"    background-color: #f39c12;\n"
"}\n"
"QPushButton#pushButton_2:hover {\n"
"    background-color: #f5b041;\n"
"}\n"
"\n"
"/* Ürün Ara */\n"
"QPushButton#pushButton_3 {\n"
"    background-color: #6c757d;\n"
"}\n"
"QPushButton#pushButton_3:hover {\n"
"    background-color: #868e96;\n"
"}\n"
"\n"
"/* Ana Ekrana Dön */\n"
"QPushButton#pushButton_4 {\n"
"    background-color: #e74c3c;\n"
"    font-size: 16px;\n"
"}\n"
"QPushButton#pushButton_4:hover {\n"
"    background-color: #ec7063;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 381, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(540, 360, 241, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(540, 390, 241, 31))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 420, 351, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 150, 241, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(420, 150, 111, 31))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 120, 261, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(680, 120, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(600, 550, 191, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 371, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 360, 111, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 390, 111, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 491, 31))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "YENİ MALZEME EKLE"))
        self.pushButton_2.setText(_translate("MainWindow", "STOĞA EKLE"))
        self.pushButton_3.setText(_translate("MainWindow", "ÜRÜN ARA"))
        self.pushButton_4.setText(_translate("MainWindow", "ANA EKRANA DÖN"))
        self.label.setText(_translate("MainWindow", "STOK ÜRÜNLERİ"))
        self.label_2.setText(_translate("MainWindow", "ÜRÜN İSMİ"))
        self.label_3.setText(_translate("MainWindow", "ÜRÜN MİKTARI"))
        self.label_4.setText(_translate("MainWindow", "STOK KONTROL SAYFASI"))
